export const data = [
  {
    image: "/card1.png",
    title: "Письмо на родину!",
    description: "Коллекция \"Истории\" №1",
    author: "Иванов И.И.",
    authorEmail: "user@mail.ru",
    date: "Создано 20 мая 2023",
  },
  {
    image: "/card2.png",
    title: "Пиши письма родным!",
    description: "Коллекция \"Истории\" №1",
    author: "Иванов И.И.",
    authorEmail: "user@mail.ru",
    date: "Создано 20 мая 2023",
  },
  {
    image: "/card3.png",
    title: "Воинам Красной Армии!",
    description: "Коллекция \"Истории\" №1",
    author: "Иванов И.И.",
    authorEmail: "user@mail.ru",
    date: "Создано 20 мая 2023",
  },
  {
    image: "/card4.png",
    title: "Письмо на родину!",
    description: "Коллекция \"Истории\" №1",
    author: "Иванов И.И.",
    authorEmail: "user@mail.ru",
    date: "Создано 20 мая 2023",
  },
  {
    image: "/card1.png",
    title: "Пиши письма родным!",
    description: "Коллекция \"Истории\" №1",
    author: "Иванов И.И.",
    authorEmail: "user@mail.ru",
    date: "Создано 20 мая 2023",
  },
  {
    image: "/card2.png",
    title: "Пиши письма родным!",
    description: "Коллекция \"Истории\" №1",
    author: "Иванов И.И.",
    authorEmail: "user@mail.ru",
    date: "Создано 20 мая 2023",
  },
];