export const data = [
  {
    id: "item-1",
    name: "Никита Калинин",
    role: "Team Lead",
    image: "/Nikita.jpg",
    link: "https://github.com/NKTKLN",
    link_name: "NKTKLN",
    description: "Руководит проектом и организует процессы разработки.",
  },
  {
    id: "item-2",
    name: "Егор Кручаев",
    role: "Data Scientist",
    image: "/Egor.jpg",
    link: "https://github.com/Spaklak",
    link_name: "Spaklak",
    description: "Отвечает за анализ данных и работу с ИИ.",
  },
  {
    id: "item-3",
    name: "Гусевский Даниил",
    role: "Backend Developer",
    image: "/Danya.jpg",
    link: "https://github.com/Danchicic",
    link_name: "Danchicic",
    description: "Разрабатывает серверную часть приложения.",
  },
  {
    id: "item-4",
    name: "Дроздов Иван",
    role: "Frontend Developer",
    image: "/Vanya.jpg",
    link: "https://github.com/improved-sleepyhead",
    link_name: "improved-sleepyhead",
    description: "Создаёт пользовательский интерфейс и логику взаимодействия.",
  },
  {
    id: "item-5",
    name: "Барматов Алексей",
    role: "Frontend Developer",
    image: "/Lesha.jpg",
    link: "https://github.com/hellpes666",
    link_name: "hellpes666",
    description: "Работает над интерфейсами и UX/UI.",
  },
]