import { Download, RefreshCw, Award } from 'lucide-react'

export const LetterPreview = () => {
	return (
		<div
			className="relative w-full max-w-4xl mx-auto rounded-md 
                  shadow-[0_4px_30px_rgba(0,0,0,0.25)] border border-dashed border-primary/30
                  group transform transition-all duration-300 hover:shadow-xl
                  min-h-[320px] h-auto"
		>
			<div
				className="bg-amber-50/90 backdrop-blur-sm px-6 py-8 
                     relative before:absolute before:inset-0 before:bg-noise-texture
                     h-[500px] flex flex-col"
			>
				<div
					className="flex items-center gap-3 border-b border-primary/40 pb-3 
                       min-h-[56px]"
				>
					<Award className="w-6 h-6 text-primary" />
					<h2
						className="font-mono text-lg tracking-wider uppercase 
                        bg-gradient-to-r from-primary to-amber-900 bg-clip-text text-transparent"
					>
						Секторный приказ №42
					</h2>
				</div>
				<div className="flex-1 overflow-y-auto pr-4 custom-scrollbar mt-4">
					<div className="font-serif text-justify italic space-y-4 pt-4">
						<p className="indent-8">
							Товарищи бойцы! В суровых условиях зимнего наступления, когда враг
							пытается сломить нашу волю артобстрелами, мы должны помнить:
							каждый окоп — крепость, каждый солдат — неприступная стена.
							Координаты сектора 58-42 требуют...
						</p>

						<div
							className={`space-y-4 transition-all duration-500 
                            opacity-70`}
						>
							<p className="indent-8">
								Подкрепление с 307-й дивизией ожидается к 04:00. Под прикрытием
								тумана осуществить переброску боеприпасов на вторую линию
								обороны... Подкрепление с 307-й дивизией ожидается к 04:00. Под
								прикрытием тумана осуществить переброску боеприпасов на вторую
								линию обороны... Подкрепление с 307-й дивизией ожидается к
								04:00. Под прикрытием тумана осуществить переброску боеприпасов
								на вторую линию обороны... Подкрепление с 307-й дивизией
								ожидается к 04:00. Под прикрытием тумана осуществить переброску
								боеприпасов на вторую линию обороны... Подкрепление с 307-й
								дивизией ожидается к 04:00. Под прикрытием тумана осуществить
								переброску боеприпасов на вторую линию обороны... Подкрепление с
								307-й дивизией ожидается к 04:00. Под прикрытием тумана
								осуществить переброску боеприпасов на вторую линию обороны...
							</p>
						</div>
					</div>
				</div>
			</div>
			<div
				className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2 
                     bg-amber-50/80 backdrop-blur-sm px-4 py-1 rounded-full 
                     border border-primary/20 shadow-sm"
			>
				<button className="flex items-center gap-2 text-sm hover:text-primary">
					<RefreshCw className="w-4 h-4" />
					Перегенерация
				</button>
				<div className="h-6 w-px bg-primary/20 mx-2" />
				<button className="hover:text-primary">
					<Download className="w-5 h-5" />
				</button>
			</div>
			<span
				className="absolute bottom-4 right-4 text-[9px] uppercase 
                      tracking-widest text-primary/30 font-mono"
			>
				Generated by SELPO
			</span>
		</div>
	)
}
